import {StyleSheet} from 'react-native';
import {ThemeColors} from '../../../theme/colors';

export const getStyles = (theme: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    settingsButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.surface,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: theme.shadow,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.textPrimary,
    },
    balanceCard: {
      backgroundColor: theme.primary,
      borderRadius: 16,
      padding: 24,
      marginHorizontal: 16,
      marginVertical: 8,
      position: 'relative',
      overflow: 'hidden',
    },
    balanceCardBackground: {
      position: 'absolute',
      right: -20,
      top: -20,
      width: 120,
      height: 120,
      backgroundColor: theme.primaryLight,
      borderRadius: 60,
      opacity: 0.2,
    },
    balanceTitle: {
      fontSize: 16,
      color: theme.textOnPrimary,
      opacity: 0.9,
      marginBottom: 8,
    },
    balanceAmount: {
      fontSize: 36,
      fontWeight: 'bold',
      color: theme.textOnPrimary,
    },
    quickActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      marginVertical: 16,
      gap: 12,
    },
    actionButton: {
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 16,
      flex: 1,
      alignItems: 'center',
      shadowColor: theme.shadow,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    actionIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.secondary,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    actionText: {
      fontSize: 14,
      color: theme.textPrimary,
      fontWeight: '600',
    },
    recentTransactions: {
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 20,
      margin: 16,
      flex: 1,
      shadowColor: theme.shadow,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    section: {
      marginTop: 24,
      paddingHorizontal: 16,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.textPrimary,
      marginBottom: 16,
    },
    emptyTransactions: {
      alignItems: 'center',
      padding: 32,
    },
    emptyTransactionsText: {
      color: theme.textSecondary,
      fontSize: 16,
      textAlign: 'center',
      marginTop: 12,
      lineHeight: 24,
    },
    transactionCard: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    transactionInfo: {
      flex: 1,
      marginLeft: 12,
    },
    transactionTitle: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.textPrimary,
      marginBottom: 4,
    },
    transactionDate: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    transactionAmount: {
      fontSize: 16,
      fontWeight: '600',
    },
    addButton: {
      position: 'absolute',
      bottom: 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
    },
  });
